name: Run Thiefs Script

on:
  schedule:
    - cron: '*/10 * * * *'  # تشغيل عند الدقيقة 50 من كل ساعة
  workflow_dispatch:      # يسمح بالتشغيل اليدوي من GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Commit updated previous_num.txt if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add previous_num.txt
          git diff --cached --quiet || git commit -m "Update previous_num.txt with latest count"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Decode Config JSON and save to file
        run: |
          echo "${{ secrets.CONFIG_JSON }}" | base64 --decode > Config.json


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth requests

      - name: Run Thiefs script
        run: python Thiefs.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
